# Generated by Django 4.0.4 on 2022-05-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicToKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'HIGH'), (2, 'NORMAL'), (3, 'LOW')])),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.keyword')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign.topic')),
            ],
        ),
    ]
