# Generated by Django 4.0.4 on 2022-05-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0002_topictokeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topictokeyword',
            name='keyword',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_to_topic', to='assign.keyword'),
        ),
        migrations.AlterField(
            model_name='topictokeyword',
            name='level',
            field=models.IntegerField(choices=[(1, 'Hoàn toàn không'), (2, 'Ít'), (3, 'Bình thường'), (4, 'Nhiều'), (5, 'Hoàn toàn có')]),
        ),
        migrations.AlterField(
            model_name='topictokeyword',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_to_keyword', to='assign.topic'),
        ),
        migrations.CreateModel(
            name='LecturerToKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Hoàn toàn không'), (2, 'Ít'), (3, 'Bình thường'), (4, 'Nhiều'), (5, 'Hoàn toàn có')])),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_to_lecturer', to='assign.keyword')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_to_keyword', to='assign.lecturer')),
            ],
        ),
    ]
