# Generated by Django 4.0.4 on 2022-06-26 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0005_mycommittee_mygroup_alter_topic_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='committee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_committee', to='assign.mycommittee'),
        ),
    ]
