# Generated by Django 4.0.4 on 2022-07-03 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0006_lecturer_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycommittee',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='committee_group', to='assign.mygroup'),
        ),
        migrations.AddField(
            model_name='topic',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topic_group', to='assign.mygroup'),
        ),
    ]
