# Generated by Django 4.0.4 on 2022-07-03 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0008_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='position',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_position', to='assign.position'),
        ),
    ]
