# Generated by Django 4.0.4 on 2022-07-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0009_lecturer_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='committee_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
