# Generated by Django 4.0.6 on 2022-07-22 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0011_lecturer_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='review_1',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='topic_review_1', to='assign.lecturer'),
        ),
        migrations.AddField(
            model_name='topic',
            name='review_2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='topic_review_2', to='assign.lecturer'),
        ),
    ]
