# Generated by Django 4.0.6 on 2022-07-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0012_topic_review_1_topic_review_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='review_count',
        ),
    ]
