# Generated by Django 4.0.6 on 2022-07-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0013_remove_lecturer_review_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='years',
        ),
    ]
