# Generated by Django 4.0.6 on 2022-07-23 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0014_department_remove_lecturer_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_department', to='assign.department'),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_department', to='assign.department'),
        ),
        migrations.AddField(
            model_name='topic',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topic_department', to='assign.department'),
        ),
    ]
