# Generated by Django 4.0.6 on 2022-07-25 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0015_keyword_department_lecturer_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='review_1',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='topic_review_1', to='assign.lecturer'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='review_2',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='topic_review_2', to='assign.lecturer'),
        ),
    ]
