# Generated by Django 4.0.6 on 2022-07-26 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assign', '0016_lecturer_review_count_alter_topic_review_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='review_1',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='topic_review_first', to='assign.lecturer'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='review_2',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='topic_review_second', to='assign.lecturer'),
        ),
    ]
